version: '3.8'  # Explicitly specify the Compose version
services:
  pylon_serial:  # Service name (keep it consistent with intent)
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pylon_serial  # Align with service name (optional, can remove if not needed)
    image: ghcr.io/svisagie/pylon_serial:beta    # Match service name for clarity
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
    volumes:
      - /data/pytes/pytes_serial.cfg:/app/pytes_serial.cfg
    devices:
      - /dev/serial/by-id/usb-Prolific_Technology_Inc._USB-Serial_Controller-if00-port0:/dev/ttyUSB0
    environment:
      - TZ=Africa/Johannesburg  # Simplified syntax
